sudo: required
language: node_js
node_js:
  - "10"
  
addons:
  chrome: stable
 
before_script:
  - npm install -g protractor
  - webdriver-manager update
  - webdriver-manager start &
  - sleep 5

script:
  - protractor conf.js